create database sitejogos;
use sitejogos;
CREATE TABLE CAR (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    DESCRICAO TEXT,
    IMGURL VARCHAR(255)
);

CREATE TABLE usuario (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    nick VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    url varchar(255) 
);

CREATE TABLE COMENTARIO (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    ID_CAR INT,
    CONTEUDO VARCHAR(255),
    FOREIGN KEY (ID_CAR) REFERENCES CAR (ID)
);



